### ISSUE TITLE
Create "Master" page in layouts.

### ISSUE THREAD

**Issue by dlopez079** [dlopez079/acronomy#19]
Created a template called "Master" in layouts.

**Comment by aarontjackson** [comment]
Created master.blade.php with a /test route to see if items render properly. I had to follow a guide to get the project to work for me. I am not sure if you will run into the same issue. But, here's the guide that I followed to be able to run the Laravel project. 

https://devmarketer.io/learn/setup-laravel-project-cloned-github-com/
