### ISSUE TITLE
DATABASE: CSV to Laravel Seed

### ISSUE THREAD

**Issue by dlopez079** [dlopez079/acronomy#29]
We have a database named Acrology in my SQL.  The database needs a table and data.

The database configuration for your application is located at config/database.php. In this file, you may define all of your database connections, as well as specify which connection should be used by default. Examples for most of the supported database systems are provided in this file.

**Comment by dlopez079** [comment]
I looked into the "config/database" file, under the mySQL section and it is getting most of its information from the env FILE located on the root directory.   I will create a branch called database_connect to make the change.

**Comment by dlopez079** [comment]
.env is a file that is ignored by git.  I made the change locally in my .env file.  I also made a change to my laptop.

**Comment by aarontjackson** [comment]
CSV file is imported into DBeaver with market data.

**Comment by dlopez079** [comment]
We successfully imported the csv file to mysql.  Issue is complete.
